namespace LabelLocker;

/// <summary>
/// Represents the result of a reservation operation, indicating success or failure,
/// and containing relevant details for either outcome.
/// </summary>
public sealed class ReservationResult
{
    /// <summary>
    /// Gets a value indicating whether the reservation operation was successful.
    /// </summary>
    public bool Success { get; }

    /// <summary>
    /// Gets an error message describing the reason for a failed reservation operation, if applicable.
    /// </summary>
    public string? ErrorMessage { get; }

    /// <summary>
    /// Gets the reservation token generated by a successful reservation operation.
    /// This token is used for identifying the reserved entity and handling concurrency.
    /// </summary>
    public byte[]? ReservationToken { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ReservationResult"/> class.
    /// This constructor is private to enforce the use of factory methods for creating instances.
    /// </summary>
    /// <param name="success">Indicates whether the reservation operation was successful.</param>
    /// <param name="reservationToken">The reservation token generated by a successful operation.</param>
    /// <param name="errorMessage">The error message for a failed reservation operation.</param>
    private ReservationResult(bool success, byte[]? reservationToken, string? errorMessage)
    {
        Success = success;
        ReservationToken = reservationToken;
        ErrorMessage = errorMessage;
    }

    /// <summary>
    /// Creates a <see cref="ReservationResult"/> instance representing a successful reservation operation.
    /// </summary>
    /// <param name="reservationToken">The reservation token generated by the operation.</param>
    /// <returns>A <see cref="ReservationResult"/> instance indicating success.</returns>
    public static ReservationResult SuccessResult(byte[] reservationToken) 
        => new ReservationResult(true, reservationToken, null);

    /// <summary>
    /// Creates a <see cref="ReservationResult"/> instance representing a failed reservation operation.
    /// </summary>
    /// <param name="errorMessage">An error message describing the reason for the failure.</param>
    /// <returns>A <see cref="ReservationResult"/> instance indicating failure.</returns>
    public static ReservationResult FailureResult(string errorMessage) 
        => new ReservationResult(false, null, errorMessage);
}